spring:
  datasource:
    url: jdbc:mysql://merchant-management.cfsw06gy817r.ap-south-1.rds.amazonaws.com:3306/merchant_management_db #${DB_URL}
    username: root #${DB_USERNAME}
    password: Password1 #${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
